### ISSUE TITLE
Class 'ProtobufMessage' not found

### ISSUE THREAD

**Issue by colin1989** [exmex/HC#4]
Can you help me.
I can not found php_protobuf.dll

**Comment by colin1989** [comment]
Solve problems by installing 32-bit software
And link https://github.com/mgp25/Chat-API/wiki/Dependencies

**Comment by lunaticCoder** [comment]
> Solve problems by installing 32-bit software
> And link https://github.com/mgp25/Chat-API/wiki/Dependencies

I had the same problem
I use this link, but I still can't run it
PHP Startup: Unable to load dynamic library  ‘’php_protobuf_nts.dll’

**Comment by exmex** [comment]
Make sure you install the correct version of library for example this library is for PHP 5.6 and for PHP Non-threadsafe only.

NTS =Not Threadsafe
TS = Threadsafe

It depends what PHP Version you have installed.

Also you need to make sure its compiled with the same compiler and compiler version as your php.

**Comment by lunaticCoder** [comment]
> Make sure you install the correct version of library for example this library is for PHP 5.6 and for PHP Non-threadsafe only.
> 
> NTS =Not Threadsafe
> TS = Threadsafe
> 
> It depends what PHP Version you have installed.
> 
> Also you need to make sure its compiled with the same compiler and compiler version as your php.

thank you
![hero](https://user-images.githubusercontent.com/8457683/69473067-0cb7be00-0ded-11ea-9567-0ba8666fa07a.png)
