### ISSUE TITLE
Cannot Run/Compile Client

### ISSUE THREAD

**Issue by rlimaeco** [exmex/HC#5]
The client has no project for visual studio or something like that to compile and create de missing CardGame.exe , and hero.exe 

In the other side , the server I could to compile but I still with errors with protobuffers in php gamesserver.

**Comment by hoctor** [comment]
I can´t make it work eather, would be nice to write a tutorial.

**Comment by lunaticCoder** [comment]
“H:\Source\HG\Client\Resource_Client\packets\” 
What's under this path？

**Comment by exmex** [comment]
> “H:\Source\HG\Client\Resource_Client\packets\”
> What's under this path？

All packets in binary, compiled format

**Comment by exmex** [comment]
Also the project has a project solution [here](https://github.com/exmex/HC/blob/master/Client/Code_Client/projects/CardGame.sln)

The project file is [here](https://github.com/exmex/HC/blob/master/Client/Code_Client/projects/Game/proj.win32/Game.vcxproj)
